#!/bin/sh
# .githooks/prepare-commit-msg

COMMIT_MSG_FILE=$1

# 병합 커밋은 무시
if grep -iqE '^merge' "$COMMIT_MSG_FILE"; then
    exit 0
fi

# 현재 브랜치명에서 타입 추출 (예: feat/#15-login → feat)
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
TYPE=$(echo "$BRANCH_NAME" | cut -d/ -f1)

# 메시지 파일에 접두사 추가
sed -i.bak -e "1s/^/${TYPE}: /" "$COMMIT_MSG_FILE"
